/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import modelo.Conectar;
import modelo.SqlCliente;
import modelo.Cliente;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author leo_t
 */
public class AgregaCliente extends javax.swing.JFrame {

    Conectar con;
    PreparedStatement consultas;
    ResultSet resultado;
    public AgregaCliente() {
        this.resultado = null;
        this.consultas = null;
        initComponents();
        this.setTitle("Formulario Cliente");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        DNI = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        celular = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JTextField();
        apellidoCliente = new javax.swing.JTextField();
        dniCliente = new javax.swing.JTextField();
        domicilioCliente = new javax.swing.JTextField();
        celularCliente = new javax.swing.JTextField();
        agregarCliente = new javax.swing.JButton();
        email = new javax.swing.JLabel();
        emailCliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Formulario de ingreso de clientes a la base de datos");
        Titulo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Veterinaria REM", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DNI.setForeground(new java.awt.Color(255, 255, 255));
        DNI.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DNI.setText("DNI:");
        DNI.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        DNI.setMinimumSize(new java.awt.Dimension(6, 22));
        DNI.setPreferredSize(new java.awt.Dimension(6, 22));
        jPanel1.add(DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 80, 30));

        apellido.setForeground(new java.awt.Color(255, 255, 255));
        apellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        apellido.setText("Apellido:");
        apellido.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        apellido.setMinimumSize(new java.awt.Dimension(6, 22));
        apellido.setPreferredSize(new java.awt.Dimension(6, 22));
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 80, 30));

        direccion.setForeground(new java.awt.Color(255, 255, 255));
        direccion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        direccion.setText("Direccion:");
        direccion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        direccion.setMinimumSize(new java.awt.Dimension(6, 22));
        direccion.setPreferredSize(new java.awt.Dimension(6, 22));
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 80, 30));

        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombre.setText("Nombre:");
        nombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        nombre.setMinimumSize(new java.awt.Dimension(6, 22));
        nombre.setPreferredSize(new java.awt.Dimension(6, 22));
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 80, 30));

        celular.setForeground(new java.awt.Color(255, 255, 255));
        celular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        celular.setText("Telefono Celular:");
        celular.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        celular.setMinimumSize(new java.awt.Dimension(6, 22));
        celular.setPreferredSize(new java.awt.Dimension(6, 22));
        jPanel1.add(celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 130, 30));

        nombreCliente.setMaximumSize(null);
        nombreCliente.setMinimumSize(new java.awt.Dimension(6, 22));
        nombreCliente.setPreferredSize(new java.awt.Dimension(8, 25));
        jPanel1.add(nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 180, 30));

        apellidoCliente.setMaximumSize(null);
        apellidoCliente.setMinimumSize(new java.awt.Dimension(6, 22));
        apellidoCliente.setPreferredSize(new java.awt.Dimension(8, 25));
        jPanel1.add(apellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 180, 30));

        dniCliente.setMaximumSize(null);
        dniCliente.setMinimumSize(new java.awt.Dimension(6, 22));
        dniCliente.setPreferredSize(new java.awt.Dimension(8, 25));
        jPanel1.add(dniCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 180, 30));

        domicilioCliente.setMaximumSize(null);
        domicilioCliente.setMinimumSize(new java.awt.Dimension(6, 22));
        domicilioCliente.setPreferredSize(new java.awt.Dimension(8, 25));
        jPanel1.add(domicilioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 180, 30));

        celularCliente.setMaximumSize(null);
        celularCliente.setMinimumSize(new java.awt.Dimension(6, 22));
        celularCliente.setPreferredSize(new java.awt.Dimension(8, 25));
        jPanel1.add(celularCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 180, 30));

        agregarCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        agregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-usuario32x32.png"))); // NOI18N
        agregarCliente.setText("Agregar");
        agregarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        agregarCliente.setOpaque(false);
        agregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(agregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 166, 40));

        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        email.setText("E-mail:");
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        email.setMinimumSize(new java.awt.Dimension(6, 22));
        email.setName(""); // NOI18N
        email.setPreferredSize(new java.awt.Dimension(6, 22));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 80, 30));

        emailCliente.setMaximumSize(null);
        emailCliente.setMinimumSize(new java.awt.Dimension(6, 22));
        emailCliente.setPreferredSize(new java.awt.Dimension(8, 25));
        jPanel1.add(emailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 180, 30));

        jDesktopPane1.setLayer(Titulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarClienteActionPerformed
       /**
        * Metodo para agregar clientes a la bd desde un boton
        * id,dni,apellido,nombre,direccion,numFijo,numCelu,Mail
        */
       SqlCliente modSql = new SqlCliente();
       Cliente modCliente = new Cliente();
       modCliente.setNombreCliente(nombreCliente.getText());
       modCliente.setApellidoCliente(apellidoCliente.getText());
       modCliente.setDni(dniCliente.getText());
       modCliente.setDomicilio(domicilioCliente.getText());
       modCliente.setNumCelular(celularCliente.getText());
       modCliente.setEmail(emailCliente.getText());

       if (modSql.AgregarCliente(modCliente)) { //validacion para agregar un usario a la db
                        JOptionPane.showMessageDialog(null, "Se guardó exitosamente el usuario");
                        limpiar(); // funcion para borrar los campos de texto y dejarlos listos para volver a agregar un usario
                    } else {
                        JOptionPane.showMessageDialog(null, "Hubo un error en el registro de usuario");
                    }
    }//GEN-LAST:event_agregarClienteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       Home.formularioAgregaCliente = null; // permite cerrar y volver a iniciar el formularioAgregaCliente
    }//GEN-LAST:event_formWindowClosing

    private void limpiar(){
    nombreCliente.setText("");
    apellidoCliente.setText("");
    dniCliente.setText("");
    domicilioCliente.setText("");
    celularCliente.setText("");
    emailCliente.setText("");
    
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AgregaCliente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DNI;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton agregarCliente;
    private javax.swing.JLabel apellido;
    private javax.swing.JTextField apellidoCliente;
    private javax.swing.JLabel celular;
    private javax.swing.JTextField celularCliente;
    private javax.swing.JLabel direccion;
    private javax.swing.JTextField dniCliente;
    private javax.swing.JTextField domicilioCliente;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailCliente;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreCliente;
    // End of variables declaration//GEN-END:variables
}
