/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficas;

import Clases.Conexion;
import Clases.SqlUsuario;
import clases.Cliente;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author leo_t
 */
public class AgregaCliente extends javax.swing.JFrame {

    Conexion con;
    PreparedStatement consultas;
    ResultSet resultado;
    public AgregaCliente() {
        this.resultado = null;
        this.consultas = null;
        initComponents();
        this.setTitle("Formulario Cliente");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        DNI = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        telFijo = new javax.swing.JLabel();
        celular = new javax.swing.JLabel();
        emailCliente = new javax.swing.JTextField();
        nombreCliente = new javax.swing.JTextField();
        apellidoCliente = new javax.swing.JTextField();
        dniCliente = new javax.swing.JTextField();
        domicilioCliente = new javax.swing.JTextField();
        celularCliente = new javax.swing.JTextField();
        telFijoCliente = new javax.swing.JTextField();
        agregarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Tahoma", 3, 17)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Formulario de ingreso de clientes a la base de datos");
        Titulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DNI.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DNI.setText("DNI:");
        DNI.setMinimumSize(new java.awt.Dimension(6, 22));
        DNI.setPreferredSize(new java.awt.Dimension(6, 22));
        jPanel1.add(DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 122, 80, 30));

        apellido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        apellido.setText("Apellido:");
        apellido.setMinimumSize(new java.awt.Dimension(6, 22));
        apellido.setPreferredSize(new java.awt.Dimension(6, 22));
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 82, 80, 30));

        direccion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        direccion.setText("Direccion:");
        direccion.setMinimumSize(new java.awt.Dimension(6, 22));
        direccion.setPreferredSize(new java.awt.Dimension(6, 22));
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 162, 80, 30));

        email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        email.setText("E-mail:");
        email.setMinimumSize(new java.awt.Dimension(6, 22));
        email.setName(""); // NOI18N
        email.setPreferredSize(new java.awt.Dimension(6, 22));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 282, 80, 30));

        nombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombre.setText("Nombre:");
        nombre.setMinimumSize(new java.awt.Dimension(6, 22));
        nombre.setPreferredSize(new java.awt.Dimension(6, 22));
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 42, 80, 30));

        telFijo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        telFijo.setText("Telefono Fijo:");
        telFijo.setMinimumSize(new java.awt.Dimension(6, 22));
        telFijo.setPreferredSize(new java.awt.Dimension(6, 22));
        jPanel1.add(telFijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 242, 110, 30));

        celular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        celular.setText("Telefono Celular:");
        celular.setMinimumSize(new java.awt.Dimension(6, 22));
        celular.setPreferredSize(new java.awt.Dimension(6, 22));
        jPanel1.add(celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 202, 130, 30));

        emailCliente.setMaximumSize(new java.awt.Dimension(6, 22));
        emailCliente.setMinimumSize(new java.awt.Dimension(6, 22));
        emailCliente.setPreferredSize(new java.awt.Dimension(8, 25));
        jPanel1.add(emailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 282, 180, 30));

        nombreCliente.setMaximumSize(new java.awt.Dimension(6, 22));
        nombreCliente.setMinimumSize(new java.awt.Dimension(6, 22));
        nombreCliente.setPreferredSize(new java.awt.Dimension(8, 25));
        jPanel1.add(nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 42, 180, 30));

        apellidoCliente.setMaximumSize(new java.awt.Dimension(6, 22));
        apellidoCliente.setMinimumSize(new java.awt.Dimension(6, 22));
        apellidoCliente.setPreferredSize(new java.awt.Dimension(8, 25));
        jPanel1.add(apellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 82, 180, 30));

        dniCliente.setMaximumSize(new java.awt.Dimension(6, 22));
        dniCliente.setMinimumSize(new java.awt.Dimension(6, 22));
        dniCliente.setPreferredSize(new java.awt.Dimension(8, 25));
        jPanel1.add(dniCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 122, 180, 30));

        domicilioCliente.setMaximumSize(new java.awt.Dimension(6, 22));
        domicilioCliente.setMinimumSize(new java.awt.Dimension(6, 22));
        domicilioCliente.setPreferredSize(new java.awt.Dimension(8, 25));
        jPanel1.add(domicilioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 162, 180, 30));

        celularCliente.setMaximumSize(new java.awt.Dimension(6, 22));
        celularCliente.setMinimumSize(new java.awt.Dimension(6, 22));
        celularCliente.setPreferredSize(new java.awt.Dimension(8, 25));
        jPanel1.add(celularCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 202, 180, 30));

        telFijoCliente.setMaximumSize(new java.awt.Dimension(6, 22));
        telFijoCliente.setMinimumSize(new java.awt.Dimension(6, 22));
        telFijoCliente.setPreferredSize(new java.awt.Dimension(8, 25));
        jPanel1.add(telFijoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 242, 180, 30));

        agregarCliente.setText("Agregar");
        agregarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        agregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(agregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 166, 37));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarClienteActionPerformed
       /**
        * Metodo para agregar clientes a la bd desde un boton
        * id,dni,apellido,nombre,direccion,numFijo,numCelu,Mail
        */
       SqlUsuario modSql = new SqlUsuario();
       Cliente modCliente = new Cliente();
       
       modCliente.setNombreCliente(nombreCliente.getText());
       modCliente.setApellidoCliente(apellidoCliente.getText());
       modCliente.setDni(dniCliente.getText());
       modCliente.setDomicilio(domicilioCliente.getText());
       modCliente.setNumCelular(celularCliente.getText());
       modCliente.setNumFIjo(telFijoCliente.getText());
       modCliente.setEmail(emailCliente.getText());
       /*ACA ME RENDI, NO SE QUE PASA -.-'*/
       
       if (modSql.AgregarUsuario(modCliente)) { //validacion para agregar un usario a la db
                        JOptionPane.showMessageDialog(null, "Se guardó exitosamente el usuario");
                        limpiar(); // funcion para borrar los campos de texto y dejarlos listos para volver a agregar un usario
                    } else {
                        JOptionPane.showMessageDialog(null, "Hubo un error en el registro de usuario");
                    }
    }//GEN-LAST:event_agregarClienteActionPerformed

    private void limpiar(){
    nombreCliente.setText("");
    apellidoCliente.setText("");
    dniCliente.setText("");
    domicilioCliente.setText("");
    celularCliente.setText("");
    telFijoCliente.setText("");
    emailCliente.setText("");
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AgregaCliente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DNI;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton agregarCliente;
    private javax.swing.JLabel apellido;
    private javax.swing.JTextField apellidoCliente;
    private javax.swing.JLabel celular;
    private javax.swing.JTextField celularCliente;
    private javax.swing.JLabel direccion;
    private javax.swing.JTextField dniCliente;
    private javax.swing.JTextField domicilioCliente;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JLabel telFijo;
    private javax.swing.JTextField telFijoCliente;
    // End of variables declaration//GEN-END:variables
}
